### PR TITLE
IP address checking during authorization

### PR DESCRIPTION
**Pull request by honigbij**
The client IP address can now be checked during the authorization process.
It is also possible to define an alternative authorization class in kippo.cfg.

An alternative authorization class (AuthRandom) is added. This class contains a checklogin method which will let a user from a certain IP address login after a random number of attempts. It will also cache username/password pairs that allow login. The parameters can be adjusted in kippo.cfg.

By default the UserDB class will be used.

### CODE REVIEW

**Comment by micheloosterhof** [comment]
I like the auth_random! I had some vague ideas for something similar as well in the past.
This pull request seems to contain everything from #29 as well, correct? Should we close that one then?

**Comment by micheloosterhof** [comment]
Also, I tested your patch and it won't let me login:


2015-03-19 06:28:32+0000 [SSHService ssh-userauth on HoneyPotTransport,2,127.0.0.1] root trying auth keyboard-interactive
2015-03-19 06:28:32+0000 [SSHService ssh-userauth on HoneyPotTransport,2,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 199, in doRead
            rval = self.protocol.dataReceived(data)
          File "/home/michel/src/kippo-git/kippo/core/ssh.py", line 223, in dataReceived
            sshserver.KippoSSHServerTransport.dataReceived(self, data)
          File "/home/michel/src/kippo-git/kippo/core/sshserver.py", line 69, in dataReceived
            self.dispatchMessage(messageNum, packet[1:])
          File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/transport.py", line 460, in dispatchMessage
            messageNum, payload)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
          File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/service.py", line 44, in packetReceived
            return f(packet)
          File "/home/michel/src/kippo-git/kippo/core/ssh.py", line 57, in ssh_USERAUTH_REQUEST
            return userauth.SSHUserAuthServer.ssh_USERAUTH_REQUEST(self, packet)
          File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/userauth.py", line 180, in ssh_USERAUTH_REQUEST
            d = self.tryAuth(method, user, rest)
          File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/userauth.py", line 154, in tryAuth
            ret = f(data)
          File "/home/michel/src/kippo-git/kippo/core/ssh.py", line 74, in auth_keyboard_interactive
            src_ip = self.transport.getPeer().address.host
        exceptions.AttributeError: HoneyPotTransport instance has no attribute 'getPeer'

**Comment by honigbij** [comment]
That's weird, I remember having that error and that is why I used to set the src_ip in the HoneyPotTransport class see pull request #29.
After that I checked the available methods in self.transport and noticed I could retrieve the ip address directly.

Could you add these lines before line 74 in ssh.py:

```
for i in dir(self.transport):
            if callable(getattr(self.transport, i)):
                print " -> %s " % repr(i)
```

And take a look which methods are available? For me it will list the getPeer method in the logging.

**Comment by micheloosterhof** [comment]
There are multiple classes called 'transport', one is a high level ssh transport, the other a lower level one. You're calling the functions for the lower level one on the high level one. There is also no 'address' attribute.
It should be

        src_ip = self.transport.transport.getPeer().host

I used this to get your version: git pull git://github.com/honigbij/kippo.git auth-checklogin-ip
Did you test the code you submitted or could it be a different Twisted version?

**Comment by honigbij** [comment]
I can reproduce the error on another device, and it is indeed the Twisted version. I have it working with Twisted 15.0.0. It gives the error with Twisted version 11.1.0.

But the self.transport.transport.getPeer().host works in both. So I will change that.
